theme = "ayu_dark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
# subwords
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'
# vim muscle memory
H = 'extend_to_line_start'
L = 'extend_to_line_end'
G = "goto_last_line"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.select]
# subwords
W = 'extend_next_sub_word_start'
B = 'extend_prev_sub_word_start'
E = 'extend_next_sub_word_end'
# vim muscle memory
H = 'extend_to_line_start'
L = 'extend_to_line_end'
