theme = "ayu_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'
H = 'extend_to_line_start'
L = 'extend_to_line_end'

[keys.select]
W = 'extend_next_sub_word_start'
B = 'extend_prev_sub_word_start'
E = 'extend_next_sub_word_end'
H = 'extend_to_line_start'
L = 'extend_to_line_end'
